base_images:
  os:
    name: ubi
    namespace: ocp
    tag: "7"
build_root:
  project_image:
    dockerfile_path: openshift-ci/Dockerfile.build_root
resources:
  '*':
    requests:
      cpu: 200m
      memory: 200Mi
tag_specification:
  name: "4.6"
  namespace: ocp
tests:
- as: prepare
  commands: make prepare
  container:
    from: src
- as: build
  commands: make build
  container:
    from: src
zz_generated_metadata:
  branch: master
  org: redhat-developer
  repo: jenkins-operator-bundle
